### ISSUE TITLE
Doesn't work in Safari and FF

### ISSUE THREAD

**Issue by lavezzi1** [gurghet/vue-smart-table#4]
I test my pages which contain smart-table component and I found that they doesn't display in Safari (last version) and Firefox. One error display in console of the browsers 

> TypeError: CSS.escape is not a function. (In 'CSS.escape(col)', 'CSS.escape' is undefined)

**Comment by gurghet** [comment]
Thanks! That is a biggie. Should be fixed in 2.4.1

**Comment by lavezzi1** [comment]
@gurghet Firefox is fixed, thanks! But Safari still has a bug. It highlights this line of code 
`if (father.addRow === true && (father.addRowCompiled[col] === false || father.addRowCompiled[col] === undefined)) {`

**Comment by gurghet** [comment]
I wasn't able to reproduce the problem on Safari 9.1.1, anyways I suspect that the CSS polyfill wasn't picked up for some reason. I forced smart table to use the polyfill even in normal browsers, so it should work in 2.4.2. Let me know.

**Comment by lavezzi1** [comment]
Yes, works like a charm. Thank you.
